/**
 * Every item transcribed from "Nextera Solution — Services & Pricing" v1.1
 * (29 September 2026). The SSR smoke test asserts each of these actually
 * renders, so a content edit cannot silently drop something the founder
 * published. Strings are written the way they appear after HTML-entity
 * decoding, except & which the smoke test matches as &amp;.
 */
export const PDF_CONTENT = {
  '§2.1 Website': [
    'Premium Website Development & Database',
    'Premium digital storefronts built to convert visitors into customers.',
    'Your website is your 24/7 salesperson',
    'Hotels & Resorts', 'Clinics & Healthcare', 'Restaurants', 'Service Businesses',
    'Educational Institutes',
    'Custom website design (no templates)', 'Online booking / enquiry system',
    'Fast loading — under 2.5 seconds', 'Database & content management (CMS)',
    'Mobile-first responsive design', 'Google Maps, reviews & trust badges',
    'SEO-ready structure from day one', 'Speed optimization & performance tuning',
    'Lead capture forms & WhatsApp integration', 'Basic analytics & conversion tracking',
    'We study your business, competitors and customers',
    'We design a custom wireframe and visual concept for your approval',
    'We build, test and optimize your website', 'We deploy and connect analytics',
    'We support, update and optimize as you grow',
    'How long does website development take?',
    'Most websites are delivered in 1–2 weeks depending on scope.',
    'Will my website work on mobile?', 'tested on real devices',
  ],
  '§2.2 Customer Experience': [
    'Smart Customer Experience System',
    'Automated systems that answer, follow up and convert — even at 2 AM.',
    'Most businesses lose customers because they respond too late',
    'Clinics & Doctors', 'Real Estate', 'Consultants', 'Coaches & Trainers',
    'Instant enquiry response automation', 'Repeated-customer loyalty automation',
    'Automated follow-up sequences', 'Patient / client follow-up system',
    'Appointment booking automation', 'Lead scoring & prioritization',
    'Smart reminders (SMS / WhatsApp)', 'Detailed reports on response times',
    'Customer feedback & review generation', 'Multi-channel inbox (all in one place)',
    'We map your customer journey and find the gaps',
    'We design an automated system for each stage', 'We set up and connect all tools',
    'We test every flow end-to-end', 'We monitor results and refine monthly',
    'Do I need to change my current tools?',
    'We build around what you already use and add what is missing.',
    'How fast can responses be automated?', 'usually within 5 seconds',
  ],
  '§2.3 Online Presence': [
    'Online Presence & Marketing Infrastructure',
    'Get found, get trusted and get chosen — across Google and social.',
    'Having a website is not enough if customers cannot find you',
    'Local Businesses', 'Service Providers', 'Franchises',
    'Local SEO (Google Maps ranking)', 'Google Ads / Meta Ads setup',
    'Google Business Profile optimization', 'Meta Pixel & GA4 analytics setup',
    'On-page SEO for all pages', 'Review management & generation',
    'Content strategy basics', 'Reputation monitoring',
    'Social media page setup & optimization', 'Monthly performance reporting',
    'We audit your current online presence',
    'We fix the foundations (listings, speed, content)',
    'We optimize your pages and profiles', 'We launch campaigns and tracking',
    'We report results and scale what works', 'How long until I see SEO results?',
    'Local SEO typically shows improvement in 4–8 weeks.', 'Do you run Google Ads?',
    'clear budgets and reporting',
  ],
  '§2.4 WhatsApp': [
    'WhatsApp Automation & CRM',
    'Your most-used app, turned into your most powerful sales channel.',
    'Indian customers love WhatsApp',
    'Retail & E-commerce', 'Coaching Institutes', 'Wholesale & Distribution',
    'WhatsApp Business setup & optimization', 'Order / booking updates automation',
    'Automated greetings & away messages', 'Simple CRM to track every conversation',
    'Product / service catalog setup', 'Team inbox for multiple staff',
    'Broadcast campaigns (with compliance)', 'Automated replies & quick replies',
    'Click-to-WhatsApp on website & ads', 'Analytics on response and conversion',
    'We audit how you currently use WhatsApp',
    'We set up and optimize your business profile',
    'We build automation flows for your use case', 'We train your team on the system',
    'We review performance and improve monthly',
    'Is this the official WhatsApp Business API?',
    'We start with the free WhatsApp Business app',
    'Can I use WhatsApp for bulk marketing?',
    'We follow WhatsApp policies to keep your number safe.',
  ],
  '§3 Bundles': [
    '₹42,000', '₹85,000', '₹1,05,000', '₹91,500', '₹1,11,500', '₹6,500', 'Best value',
    'Website Development only', 'Website + Customer Experience + Online Presence',
    'Everything — complete growth system', 'Custom website (up to 5 pages)',
    'Basic SEO setup', 'Lead capture forms + WhatsApp button',
    'Hosting & domain configuration', '1-month free support', 'Everything in Silver',
    'Automated enquiry response system', 'Local SEO optimization',
    'Appointment booking automation', 'Analytics & tracking setup',
    'Google Business Profile setup', '3-month free support', 'Everything in Gold',
    'WhatsApp automation & CRM setup', 'Priority support', 'Review generation system',
    'Monthly strategy review (6 months)', 'Social media profile setup',
    '6-month free support', 'Entry-level price. Custom-quoted for larger scopes.',
  ],
  '§4 Component values': [
    '₹1,31,500', '₹28,000', '₹21,500', '₹25,000',
    'Website Development (Silver scope)', 'Online Presence & Local SEO',
    'Review generation system', 'Social profile setup', 'Priority & strategy support',
    'Component values are indicative',
  ],
  '§5 Starting points': ['Category starting points', 'Custom quote'],
  '§6 Add-ons': [
    'Logo & brand identity design', 'Content writing & photography',
    'Google Ads management', 'Meta Ads management', 'Monthly SEO packages',
    'Advanced analytics dashboards', 'Multi-language support', 'Video & 3D production',
    'Training sessions for your team', 'One-time, custom quote', 'Monthly, custom quote',
  ],
  '§7 Support plans': [
    'Starter', 'Growth', 'Scale', 'Updates, uptime monitoring, monthly report',
    'Starter + content updates, optimization, priority support',
    'Growth + monthly strategy review, campaigns, everything',
    'Best for a new website that needs to stay online and secure.',
    'Best for businesses actively publishing and optimizing.',
    'Best for teams running continuous growth campaigns.',
  ],
  '§8 Framework': [
    'Discover', 'Deploy', 'Optimize', 'find the real growth gaps',
    'system blueprint for your approval', 'website, automation and tracking',
    'test what works and refine continuously', 'campaigns, content and monthly strategy',
  ],
  '§9 Pricing FAQ': [
    'Why do you not show exact prices?', 'What determines the final pricing?',
    'Do you offer payment plans?', 'Are there any hidden charges?',
    'What if I only need a website?', 'advance and milestone payments',
    'Hosting and domain costs are transparently itemized',
    'That is exactly what the Silver bundle covers.',
  ],
  '§10 Payment terms': [
    'A booking advance confirms your project and reserves your delivery slot.',
    'milestone payments released as each stage is approved', 'there are no hidden charges',
    'owned by you', 'refundable if work has not started (within 7 days)',
    'Book a free 30-minute consultation', 'clear, itemized proposal and timeline',
    'Approve the scope and pay the booking advance', 'We build, launch and optimize',
  ],
}

export const PDF_ITEM_COUNT = Object.values(PDF_CONTENT).reduce(
  (n, list) => n + list.length,
  0,
)
